// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDLRCAY6pAhP8aFgytOMHDWYhu-FndcjQ',
    appId: '1:170676369947:web:c370bee299b8df039096be',
    messagingSenderId: '170676369947',
    projectId: 'constructions-4daac',
    authDomain: 'constructions-4daac.firebaseapp.com',
    storageBucket: 'constructions-4daac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JosHDqiu0019UdTvwtQtX9lIFlXOeDY',
    appId: '1:170676369947:android:91db1714a55ed3f99096be',
    messagingSenderId: '170676369947',
    projectId: 'constructions-4daac',
    storageBucket: 'constructions-4daac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhYIV13D6E-TT3ueqPjZsoABJqPl_1FeA',
    appId: '1:170676369947:ios:1b3098978c56d28a9096be',
    messagingSenderId: '170676369947',
    projectId: 'constructions-4daac',
    storageBucket: 'constructions-4daac.appspot.com',
    iosBundleId: 'com.example.construction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhYIV13D6E-TT3ueqPjZsoABJqPl_1FeA',
    appId: '1:170676369947:ios:b9cbfe8860fd98119096be',
    messagingSenderId: '170676369947',
    projectId: 'constructions-4daac',
    storageBucket: 'constructions-4daac.appspot.com',
    iosBundleId: 'com.example.construction.RunnerTests',
  );
}
