// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqE74rC9JW-Z5bO--py0GcJK-G-eiRRF0',
    appId: '1:990459112588:web:7624d030aa8479d106dfa9',
    messagingSenderId: '990459112588',
    projectId: 'globalconstructions-a1add',
    authDomain: 'globalconstructions-a1add.firebaseapp.com',
    storageBucket: 'globalconstructions-a1add.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAer4S6Q_IHr9nlnTtUd3yovrRPVpZ2WYk',
    appId: '1:990459112588:android:8fbf0a2cd1d2b04d06dfa9',
    messagingSenderId: '990459112588',
    projectId: 'globalconstructions-a1add',
    storageBucket: 'globalconstructions-a1add.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7E8FYNC5fX2mW-P_iPBr1eDbBhVyN2qU',
    appId: '1:990459112588:ios:451a4c9cbeefcab806dfa9',
    messagingSenderId: '990459112588',
    projectId: 'globalconstructions-a1add',
    storageBucket: 'globalconstructions-a1add.appspot.com',
    iosBundleId: 'com.example.construction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7E8FYNC5fX2mW-P_iPBr1eDbBhVyN2qU',
    appId: '1:990459112588:ios:5f3162f65b15ac6b06dfa9',
    messagingSenderId: '990459112588',
    projectId: 'globalconstructions-a1add',
    storageBucket: 'globalconstructions-a1add.appspot.com',
    iosBundleId: 'com.example.construction.RunnerTests',
  );
}
